/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sidekiq_rx.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(0ee75829dd916db552bb27b2caaa35ef)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <sidekiq/sidekiq_rx.h>
// pydoc.h is automatically generated in the build directory
#include <sidekiq_rx_pydoc.h>

void bind_sidekiq_rx(py::module& m)
{

    using sidekiq_rx    = gr::sidekiq::sidekiq_rx;


    py::class_<sidekiq_rx,
        std::shared_ptr<sidekiq_rx>>(m, "sidekiq_rx", D(sidekiq_rx))

        .def(py::init(&sidekiq_rx::make),
           py::arg("sample_rate"),
           py::arg("gain"),
           py::arg("gain_mode"),
           py::arg("frequency"),
           py::arg("bandwidth"),
           py::arg("sync_type"),
           py::arg("num_items"),
           py::arg("taps"),
           D(sidekiq_rx,make)
        )
        



        ;




}








