/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(sidekiq_tx.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7d68f1a5058bdc9abc01f006ffa4deff)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <sidekiq/sidekiq_tx.h>
// pydoc.h is automatically generated in the build directory
#include <sidekiq_tx_pydoc.h>

void bind_sidekiq_tx(py::module& m)
{

    using sidekiq_tx    = gr::sidekiq::sidekiq_tx;


    py::class_<sidekiq_tx,
        std::shared_ptr<sidekiq_tx>>(m, "sidekiq_tx", D(sidekiq_tx))

        .def(py::init(&sidekiq_tx::make),
           py::arg("sample_rate"),
           py::arg("attenuation"),
           py::arg("frequency"),
           py::arg("bandwidth"),
           py::arg("sync_type"),
           py::arg("suppress_tune_transients"),
           py::arg("dataflow_mode"),
           py::arg("buffer_size"),
           py::arg("taps"),
           D(sidekiq_tx,make)
        )
        



        ;




}








